# Generated by Django 4.1.1 on 2022-09-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, unique=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('calories', models.IntegerField(verbose_name='calories')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images')),
                ('in_stock', models.BooleanField(default=True, verbose_name='in_stock')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productcategory')),
            ],
        ),
    ]
